const UPPERCASE_CHARACTER_REGEX = /[A-Z]/
const LOWER_CHARACTER_REGEX = /[a-z]/
const NUMBER_CHARACTER_REGEX = /[0-9]/
const LATIN_CHARACTER_REGEX = /^[A-Za-z0-9!@#\$%\^\&*\-_]+$/

export {
  LATIN_CHARACTER_REGEX,
  LOWER_CHARACTER_REGEX,
  NUMBER_CHARACTER_REGEX,
  UPPERCASE_CHARACTER_REGEX
}
